
import { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ThemeProvider } from "@/context/theme";
import TopNav from "@/components/nav/TopNav";


export const metadata: Metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme ="dark">
      <ThemeProvider>
        <body>
          <TopNav />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
